acnl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from acnl.sitemap import EncSitemap
from acnl.sitemap import ViewSitemap

sitemaps = {
    'views': ViewSitemap,
    'encyclopedia': EncSitemap,
}

urlpatterns = [
    path('nook/', admin.site.urls),
    path('', include('encyclopedia.urls')),
    path('', include('creatures.urls')),

    path('', include('creatures.api_urls'))
    #path('sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from encyclopedia.views.availableunits import AvailableUnitsView
from encyclopedia.views.encyclopedia import EncyclopediaPageView, EncyclopediaView
from encyclopedia.views.lastchanceunits import LastChanceUnitsView

app_name = 'encyclopedia'

urlpatterns = [
    path('', LastChanceUnitsView.as_view(), name='last-chance-units'),
    path('available/', AvailableUnitsView.as_view(), name='available-units'),
    path('encyclopedia/', EncyclopediaView.as_view(), name='encyclopedia'),

    path('api/encyclopedia/<int:pk>/<int:page>/', EncyclopediaPageView.as_view(), name='page'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ meta_description }}">
    <title>{% if page_title %}{{ page_title }} |{% endif %} Animal Crossing New Leaf Encyclopedia</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/acnl.gen.css' %}" >
</head>
<body>
    {% include 'base/header.html' %}
    <main class="grid padding">{% block main %}{% endblock %}</main>
    {% include 'base/footer.html' %}
    {% block script %}{% endblock %}
</body>
</html>

templates/base/footer.html
<footer class="grid padding">
    <section class="cs4 cm8 cl8 clm2">
        <div class="block grid-fluid">
            <div class="cs4 cm8 cl7">
                <p>First of all this is non-commercial fan site.<br>
                    Our goal was recreating actual ingame encyclopedia.<br>
                    Most of the data we took from <a href="http://animalcrossing.wikia.com/" target="_blank">Animal Crossing Wikia</a> and <a href="https://nookipedia.com" target="_blank">Nookipedia</a></p>
            </div>
            <div class="cs4 cm8 cl5">
                <p><a href="http://www.animal-crossing.com/newleaf/" target="_blank">Animal Crossing New Leaf web site.</a></p>
                <p><a href="http://www.nintendo.com/" target="_blank">Nintendo web site.</a></p>
            </div>
            <div class="cs4 cm8 cl12">
                <p> {{ PROJECT_VERSION }} | 2017 &ndash; {% now "Y" %} |
                    Powered by <a href="https://www.djangoproject.com/" target="_blank" rel="noopener nofollow">Django {{ DJANGO_VERSION }}</a>,
                    <a href="Http://www.postgresql.org/" target="_blank" rel="noopener nofollow">PosgreSQL</a> |
                    <a href="https://gitlab.com/alexmitroff/acnl/" target="_blank"  rel="noopener nofollow">Sources on GitLab</a>.</p>
            </div>
        </div>
    </section>
</footer>

templates/base/header.html
{% load static %}
<header class="grid padding">
    <section class="cs4 cm4 cmm2 cl4 clm4">
        <img class="logo" src="{% static 'img/logo/logo.png' %}" alt="Animal Crossing New Leaf Logo">
    </section>
    <section class="cs4 cm8 cl8 clm2">
        <nav>
            <ul>
                {% url 'encyclopedia:last-chance-units' as url_last %}
                <li><a class="button
                             {% ifequal request.path url_last %}active{% endifequal %}"
                       href="{{ url_last }}" class="menu-item">{{ mon }} last chance</a></li>

                {% url 'encyclopedia:available-units' as url_available %}
                <li><a class="button
                             {% ifequal request.path url_available %}active{% endifequal %}"
                       href="{{ url_available }}" class="menu-item">Available in {{mon}}</a></li>

                {% url 'encyclopedia:encyclopedia' as url_encyclopedia %}
                {% url 'encyclopedia:unit' unit.id as url_unit %}
                <li><a class="button
                              {% ifequal request.path url_encyclopedia %}active{% endifequal %}
                              {% ifequal request.path url_unit %}active{% endifequal %}"
                        href="{{ url_encyclopedia }}">Encyclopedia</a></li>
            </ul>
        </nav>
    </section>
</header>