acnl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from acnl.sitemap import EncSitemap
from acnl.sitemap import ViewSitemap

sitemaps = {
    'views': ViewSitemap,
    'encyclopedia': EncSitemap,
}

urlpatterns = [
    path('nook/', admin.site.urls),
    path('', include('encyclopedia.urls')),
    path('', include('creatures.urls')),

    path('', include('creatures.api_urls'))
    #path('sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from encyclopedia.views.availableunits import AvailableUnitsView
from encyclopedia.views.encyclopedia import EncyclopediaPageView, EncyclopediaView
from encyclopedia.views.lastchanceunits import LastChanceUnitsView

app_name = 'encyclopedia'

urlpatterns = [
    path('', LastChanceUnitsView.as_view(), name='last-chance-units'),
    path('available/', AvailableUnitsView.as_view(), name='available-units'),
    path('encyclopedia/', EncyclopediaView.as_view(), name='encyclopedia'),

    path('api/encyclopedia/<int:pk>/<int:page>/', EncyclopediaPageView.as_view(), name='page'),
]

templates/include/analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59812083-1', 'auto');
  ga('send', 'pageview');

</script>

templates/include/creature-pagination.html
<section class="grid-fluid">
{% include 'include/creature-thumb.html' %}
</section>

{% if creatures.paginator.page_range %}
<ul class="encyclopedia-pagination"
        hx-trigger="click"
        hx-target="#id_{{ section_slug }}"
        hx-swap="innerHTML"
>

{% if creatures.has_previous %}
    <li><button type="button"
         class="pagination-nav-arrow"
         hx-get="{% url 'encyclopedia:page' pk=section_pk page=creatures.previous_page_number %}"
         >&larr;</button></li>
{% endif %}

{% for page_number in creatures.paginator.page_range %}
    <li><button type="button"
         {% if creatures.number == page_number %}
         class="active"
         {% endif %}
         hx-get="{% url 'encyclopedia:page' pk=section_pk page=page_number %}"
        >&bullet;</button></li>
{% endfor %}

{% if creatures.has_next %}
    <li><button type="button"
         hx-get="{% url 'encyclopedia:page' pk=section_pk page=creatures.next_page_number %}"
         class="pagination-nav-arrow"
         >&rarr;</button></li>
{% endif %}
</ul>
{% endif %}

templates/include/creature-thumb.html
{% for creature in creatures %}
<a class="creature-thumb cs2 cm2 cl2" href="{{ creature.url }}">
    <div class="creature-preview">
        <div class="creature-preview-pic" style="border-color: {{ creature.rarity.hsl_color }}">
            <img src="{{ creature.picture_url }}" alt="{{ creature.name }} in New Leaf">
        </div>
        {% if not creature.was_in_previous_month and creature.is_available_this_month %}
        <div class="creature-banner">new</div>
        {% endif %}
    </div>
    <p>{{ creature.name }}</p>
</a>
{% endfor %}